### ISSUE TITLE
Use an editor for the body field

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/SimpleCmsBundle#132]
Same as https://github.com/symfony-cmf/ContentBundle/issues/122

(maybe this should be built into the CoreBundle/CreateBundle as an extension?)

**Comment by dbu** [comment]
+1

i would not mix this with create.js (which is about frontend editing and
using its own channel to save the content). if i am not completely
confused, we can install something like egeloen/ckeditor-bundle in the
sandbox and have a config on the admin for wysiwyg text fields and make
them type `ckeditor` if egeloen is around: `->add('body', 'ckeditor')`
and textarea otherwise (and see if we can make the textarea bigger in
that case)
